server:
  additionalApplications:
    - name: challenge
      namespace: mateusclira
      project: challenge
      source:
        repoURL: https://github.com/mateusclira/challenge-cloud-engineer.git
        targetRevision: main
        path: manifests/cluster
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: false
          selfHeal: false