server:
  additionalApplications:
    - name: cluster-config
      namespace: webapp
      project: mateusclira
      source:
        repoURL: https://github.com/mateusclira/challenge-cloud-engineer.git
        targetRevision: main
        path: argocd/manifests/cluster
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: false
          selfHeal: false