kind: Cluster
  apiVersion: kind.x-k8s.io/v1alpha4
  nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 30201
      hostPort: 30201
      listenAddress: "0.0.0.0"


#just a file test for creating a cluster without Terraform. Turns out it was unecessary since I figure out how to do it on terraform.