apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-ca
spec:
  dnsNames:
    - yourdomain.here
  secretName: my-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer