apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdeploy
  labels:
    app: challenge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: challenge
  template:
    metadata:
      labels:
        app: challenge
    spec:
      containers:
        - name: webservice
          image: bitnami/wordpress-nginx:latest
          ports:
          - containerPort: 9000