apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mateusclira-ingress-tls
spec:
  tls:
  - hosts:
      - https://wordpress.default.svc
    secretName: mateusclira-tls
  rules:
  - host: https://wordpress.default.svc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service
            port:
              number: 80
