apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: mateusclira
  namespace: default
spec:
  tls:
  - hosts:
    - www.mateusebelzinha.com.br
    secretName: mateusliratls
  rules:
  - host: www.mateusebelzinha.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: service-moby
            port: 
              number: 80