apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mateuscliraingress
spec:
  tls:
  - hosts:
      - moby
    secretName: mateuscliratls
  rules:
  - host: moby
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service
            port:
              number: 80
