kind: Service
apiVersion: v1
metadata:
  annotations: 
    cloud.google.com/neg: "{\"ingress\":false}"
  name: service-moby
spec: 
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: challenge