apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: challenge
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name: web
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: challenge