apiVersion: v1
kind: Service
metadata:
  name: service-moby
  labels:
    app: challenge
spec:
  selector:
    app: challenge
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 9000